### ISSUE TITLE
Node Js and NPM Install

### ISSUE THREAD

**Issue by DigiTecK3D** [mnedelchev-vn/pancakeswap-sniper-bot#1]
Hello, I'm a Windows user trying to install node js and npm and no matter what I do I run into issues when I go to run NPM Install, so it would be good to know more information if possible on what are the exact requirements cause when I got install to use the bot I get this kind of error, Thank you!

![image](https://user-images.githubusercontent.com/5471872/124421726-af555400-dd27-11eb-9feb-7c05c97d7ecf.png)

**Comment by DigiTecK3D** [comment]
`12049 warn pancakeswap-sniper-bot@1.0.0 No repository field.
12050 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
12051 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
12052 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
12052 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
12052 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
12052 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
12053 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
12054 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
12055 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
12055 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
12055 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
12055 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
12056 verbose stack Error: scrypt@6.0.3 install: `node-gyp rebuild`
12056 verbose stack Exit status 1
12056 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
12056 verbose stack     at EventEmitter.emit (events.js:375:28)
12056 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12056 verbose stack     at ChildProcess.emit (events.js:375:28)
12056 verbose stack     at maybeClose (internal/child_process.js:1055:16)
12056 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
12057 verbose pkgid scrypt@6.0.3
12058 verbose cwd C:\Users\migue\Downloads\pancakeswap-sniper-bot-main
12059 verbose Windows_NT 10.0.19042
12060 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
12061 verbose node v14.17.2
12062 verbose npm  v6.14.13
12063 error code ELIFECYCLE
12064 error errno 1
12065 error scrypt@6.0.3 install: `node-gyp rebuild`
12065 error Exit status 1
12066 error Failed at the scrypt@6.0.3 install script.
12066 error This is probably not a problem with npm. There is likely additional logging output above.
12067 verbose exit [ 1, true ]`

**Comment by DigiTecK3D** [comment]
12049 warn pancakeswap-sniper-bot@1.0.0 No repository field.
12050 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
12051 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
12052 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
12052 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
12052 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
12052 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
12053 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
12054 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
12055 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
12055 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
12055 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
12055 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
12056 verbose stack Error: scrypt@6.0.3 install: `node-gyp rebuild`
12056 verbose stack Exit status 1
12056 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
12056 verbose stack     at EventEmitter.emit (events.js:375:28)
12056 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12056 verbose stack     at ChildProcess.emit (events.js:375:28)
12056 verbose stack     at maybeClose (internal/child_process.js:1055:16)
12056 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
12057 verbose pkgid scrypt@6.0.3
12058 verbose cwd C:\Users\migue\Downloads\pancakeswap-sniper-bot-main
12059 verbose Windows_NT 10.0.19042
12060 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
12061 verbose node v14.17.2
12062 verbose npm  v6.14.13
12063 error code ELIFECYCLE
12064 error errno 1
12065 error scrypt@6.0.3 install: `node-gyp rebuild`
12065 error Exit status 1
12066 error Failed at the scrypt@6.0.3 install script.
12066 error This is probably not a problem with npm. There is likely additional logging output above.
12067 verbose exit [ 1, true ]

**Comment by mnedelchev-vn** [comment]
Hey, the issues are related to your node or npm versions, not to the bot. I just made a fresh clone and everything went smoothly with the following versions:
npm 6.4.1
node 10.12.0

I suggest before using the bot you should try with the versions which I listed above, closing the ticket issue for now.

**Comment by DigiTecK3D** [comment]
Hello thank you for the update, Installed node 10.12.0 and npm 6.4.1 and I'm still running into those exact errors again 
`C:\Users\migue\Downloads\pancakeswap-sniper-bot-main\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\Users\migue\Downloads\pancakeswap-sniper-bot-main\node_modules\scrypt\build\..\scrypt\win\include\config.h
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:407:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\migue\Downloads\pancakeswap-sniper-bot-main\node_modules\scrypt
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN pancakeswap-sniper-bot@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\migue\AppData\Roaming\npm-cache\_logs\2021-07-10T00_10_02_430Z-debug.log`

**Comment by DigiTecK3D** [comment]
well figured out what it is, if anyone else comes along, in the package.json file on line 14 "web3": "1.0.0-beta.36" changing this to a newer version like "web3": "^1.3.6" then the file will install fine for me using the latest version of node.js and the version recommended up top.
