### ISSUE TITLE
Missing or wrong tokenaddress parameter

### ISSUE THREAD

**Issue by ironclad128** [mnedelchev-vn/pancakeswap-sniper-bot#2]
after doing everything mentioned, i get the error that the token address is missing or wrong.

// ======================== REQUIRED PARAMETERS ========================
    if (!projectData.utils.propertyExists(args, '0xa73c2c0f359ab3a3bf6c9022adb84ba21609d548') || args.tokenAddress == '' || args.tokenAddress == null || args.tokenAddress == undefined || args.tokenAddress.length != 42) {
        return console.error('Missing or wrong tokenAddress parameter.');
    } else if (!projectData.utils.propertyExists(args, '1') || args.buyingBnbAmount == '' || args.buyingBnbAmount == null || args.buyingBnbAmount == undefined) {
        return console.error('Missing or wrong buyingBnbAmount parameter.');

terminal:
/pancakeswap-sniper-bot.js 
Welcome to PancakeSwap Sniper bot!
Missing or wrong tokenAddress parameter.

**Comment by Peaceislove1996** [comment]
same problem

**Comment by mnedelchev-vn** [comment]
Hello, there is nothing wrong with the current code of the bot. From the example you've attached I can see that you've to tried to modify my code, but there are issues with it. Before making code changes you might wanna check out few tutorials how javascripts and NodeJS are working. If not, then just stick to using the bot by terminal commands ( as suggested in the github documentation ).

**Comment by ironclad128** [comment]
hi, thanks for the response. i didnt do any edits in the code. i ran it as it was. but still got that error.

**Comment by mnedelchev-vn** [comment]
Yes you've done edits, the piece of code that you've attached is modified and different from mine, example: What is ``'0xa73c2c0f359ab3a3bf6c9022adb84ba21609d548'`` doing in the code? This is not placed by me.

Download a fresh version of my code and try to use the bot again.

**Comment by ironclad128** [comment]
my bad. i might have inserted token address in the wrong line. would you tell me where to put the token address of the coin

**Comment by ironclad128** [comment]
i meant giving all the info in the file directly instead of command prompt

**Comment by mnedelchev-vn** [comment]
@ironclad128 Well you're not supposed to use the bot that way. The suggested way is to use it by terminal commands, if you want to use hardcoded values then you need coding knowledge to understand how the code actually works.
