### ISSUE TITLE
where can i add my api key and contract adress to buy and amount inside the code.js

### ISSUE THREAD

**Issue by Peaceislove1996** [mnedelchev-vn/pancakeswap-sniper-bot#4]
where can i add my api key and contract adress to buy and amount inside the code.js without copying the Sample terminal command

**Comment by mnedelchev-vn** [comment]
Hello, first of all there is no such thing as "api key" in my bot, you probably meant **### senderPrivateKey**. It's easiest for you to copy the sample command from the docs and to replace the sample parameters with your own parameters, then open a terminal in the bot folder and fire the command. But if for some reason you want to stick to not using the terminal command and hardcoding the parameters, then you will have to open the ```pancakeswap-sniper-bot.js``` file into coding editor and then to find the place where you can hardcode your parameters.
