### ISSUE TITLE
hi i got this error 

### ISSUE THREAD

**Issue by 252furkan** [mnedelchev-vn/pancakeswap-sniper-bot#6]
**Hi i got this error . How can i fix it ? Thanks a lot**  

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'cronr'
Require stack:
- C:\sniper\pancakeswap-sniper-bot.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:745:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:961:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:92:18)←[39m
    at Object.<anonymous> (C:\sniper\pancakeswap-sniper-bot.js:3:15)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1072:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:937:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:778:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\sniper\\pancakeswap-sniper-bot.js'←[39m ]

**Comment by mnedelchev-vn** [comment]
Hello, for some reason package ```cronr``` has not been downloaded at your side. Run terminal command ```npm i``` inside the bot directory to download all the needed packages in order to use the bot.
