### ISSUE TITLE
Token selling opportunity

### ISSUE THREAD

**Issue by applebulla** [mnedelchev-vn/pancakeswap-sniper-bot#8]
Hello! First of all I want to say thanks to you for your time and effort spent on the project which works great for me!
But I want to ask you a question: is there any way to modify code for selling token?

**Comment by Moka51** [comment]
That would be awesome, thanks dev for this amazing bot

**Comment by mnedelchev-vn** [comment]
Hey guys, happy to see people using the bot.

@applebulla @Moka51  If you have the skills and the knowledge to upgrade the bot to sell on different conditions then you're free to do it. It's open source bot publicly shared for everyone who wishes to use it. I never needed a sell bot so I didn't build this logic.

@deeqoo Correct, this is the initialization of the external node that the bot is using. You can edit the bot command to work with the BSC testnet if you want to play around with it and then when you're familiar with the bot you can start using it on the BSC mainnet.
